import { useLocation } from "react-router-dom";
import { PolicyLayout, type PolicySection } from "@/components/PolicyLayout";

type Policy = { eyebrow: string; title: string; summary: string; sections: PolicySection[] };

const sharedContact: PolicySection = {
  id: "contact",
  title: "Contact and updates",
  body: [
    "Questions about this policy or Freshira’s website can be submitted through the Contact page. Please avoid sending payment card details or other sensitive information through a general enquiry form.",
    "Freshira may revise these materials as its services, operational practices, or legal obligations change. The version displayed on this website applies from the date it is published.",
  ],
};

const policies: Record<string, Policy> = {
  "/privacy-policy": {
    eyebrow: "Legal information",
    title: "Privacy Policy",
    summary: "How information is handled when you browse Freshira’s website or submit an enquiry.",
    sections: [
      { id: "scope", title: "Scope", body: ["This policy applies to information collected through Freshira’s website, including information that you choose to provide through an enquiry form. It does not apply to third-party websites, services, or platforms that may be linked from this site."] },
      { id: "information", title: "Information we may receive", body: ["Information you provide may include your name, business name, email address, telephone number, and the contents of your message. Standard technical information, such as browser type, device information, and pages viewed, may also be processed to operate and improve the website."], bullets: ["Information you submit directly through a form", "Technical and usage data generated by your browser", "Correspondence relating to an enquiry or support request"] },
      { id: "use", title: "How information is used", body: ["Freshira may use information to respond to enquiries, maintain the website, understand service interest, protect against misuse, and meet applicable legal obligations. Marketing communications should only be sent where a valid basis exists and recipients can opt out."] },
      { id: "sharing", title: "Sharing and retention", body: ["Information may be handled by service providers that support hosting, communications, security, or business operations. Freshira should require those providers to use information only for authorised purposes and to apply appropriate safeguards.", "Information should be retained only for as long as needed for the purpose for which it was collected, to resolve a request, or to meet a legal requirement."] },
      { id: "choices", title: "Your choices", body: ["Subject to applicable law, you may ask about access to, correction of, or deletion of personal information held about you. Freshira may need to verify a request and may retain limited information where required or permitted by law."] },
      sharedContact,
    ],
  },
  "/terms-and-conditions": {
    eyebrow: "Legal information",
    title: "Terms of Use",
    summary: "The conditions for using Freshira’s informational website and digital services.",
    sections: [
      { id: "acceptance", title: "Acceptance", body: ["By accessing this website, you agree to use it lawfully and in accordance with these terms. If you do not agree, please do not use the site."] },
      { id: "website", title: "Website information", body: ["Freshira aims to present useful, current information about its business and offerings. Product information, availability, pricing, service areas, and operating capabilities may change and should be confirmed directly with Freshira before any commercial decision is made."] },
      { id: "responsible-use", title: "Responsible use", body: ["You must not interfere with the website, attempt unauthorised access, introduce harmful code, or use the site in a way that breaches applicable law or another person’s rights."] },
      { id: "intellectual-property", title: "Content and intellectual property", body: ["The website’s original content, branding, and design are protected by applicable intellectual-property laws. You may view the site for personal or legitimate business purposes, but you may not reproduce or use protected material without permission except where law permits."] },
      { id: "liability", title: "Third parties and liability", body: ["Links to third-party services are provided for convenience. Freshira does not control those services and their terms and privacy practices apply separately.", "To the extent permitted by law, Freshira is not responsible for losses arising from reliance on general website content, interruptions outside its reasonable control, or the actions of third parties."] },
      sharedContact,
    ],
  },
  "/shipping-policy": {
    eyebrow: "Service information",
    title: "Delivery & Shipping Policy",
    summary: "The principles that apply when Freshira offers delivery for a confirmed order.",
    sections: [
      { id: "availability", title: "Service availability", body: ["Delivery availability, service areas, cutoff times, and fees depend on the confirmed order, delivery address, and operational capacity. Any available options should be shown before an order is placed."] },
      { id: "dispatch", title: "Processing and dispatch", body: ["Freshira may need to verify an order, confirm product availability, and prepare goods before dispatch. Estimated delivery times are guidance rather than guarantees and may change due to weather, traffic, supply conditions, or other events outside reasonable control."] },
      { id: "delivery", title: "Receiving an order", body: ["Customers should provide an accurate delivery address and a reachable contact number. Where a delivery cannot be completed because of incorrect details, access restrictions, or recipient unavailability, Freshira may need to arrange a further attempt or contact the customer for instructions."] },
      { id: "issues", title: "Delivery issues", body: ["Please raise missing, damaged, or quality-related concerns as soon as reasonably possible after delivery, with the order details and any helpful photos. Freshira will review the information in line with the applicable return or refund terms."] },
      sharedContact,
    ],
  },
  "/return-policy": {
    eyebrow: "Service information",
    title: "Return Policy",
    summary: "How Freshira may assess return requests for items supplied through a confirmed order.",
    sections: [
      { id: "eligibility", title: "Return eligibility", body: ["Eligibility depends on the product type, condition, and the reason for the request. Perishable items may require a prompt quality report because their condition can change quickly after delivery."] },
      { id: "request", title: "Making a request", body: ["A return request should include an order reference, a short description of the concern, and supporting photographs where appropriate. Freshira may ask for additional details before confirming the next step."] },
      { id: "outcome", title: "Review and outcome", body: ["After review, Freshira may offer a replacement, store credit, refund, collection arrangement, or another appropriate resolution, where applicable. The available outcome will depend on the order and the reason for the request."] },
      sharedContact,
    ],
  },
  "/refund-policy": {
    eyebrow: "Service information",
    title: "Refund Policy",
    summary: "How any approved refund is assessed and issued for a confirmed order.",
    sections: [
      { id: "review", title: "Assessment", body: ["Refund requests are assessed in line with the product, delivery record, payment method, and any information supplied with the request. Approval is not automatic and may depend on the circumstances of the order."] },
      { id: "method", title: "Refund method and timing", body: ["Where a refund is approved, it should normally be issued to the original payment method unless another method is agreed or required. Processing times can vary between payment providers and financial institutions."] },
      { id: "exceptions", title: "Exceptions", body: ["A refund may not be available where goods have been used, stored improperly, reported outside the applicable review period, or where the issue cannot reasonably be verified. Statutory consumer rights are not limited by this policy."] },
      sharedContact,
    ],
  },
  "/cancellation-policy": {
    eyebrow: "Service information",
    title: "Cancellation Policy",
    summary: "How a customer may request a change or cancellation before fulfilment.",
    sections: [
      { id: "request", title: "Requesting cancellation", body: ["A cancellation request should be made as soon as possible with the order reference and contact details. Freshira will confirm whether the order can still be changed or cancelled before dispatch or fulfilment begins."] },
      { id: "processing", title: "Orders already in progress", body: ["An order may no longer be cancellable once goods have been prepared, allocated, dispatched, or handed to a delivery partner. In that situation, return or refund terms may apply instead."] },
      { id: "refunds", title: "Approved cancellation refunds", body: ["If payment has been taken and a cancellation is approved, the amount and method of any refund will be confirmed to the customer. Provider processing times may apply."] },
      sharedContact,
    ],
  },
  "/cookie-policy": {
    eyebrow: "Website information",
    title: "Cookie Policy",
    summary: "How browser storage technologies may support Freshira’s website experience.",
    sections: [
      { id: "cookies", title: "What cookies are", body: ["Cookies are small files stored by a browser. Similar technologies can help a website remember choices, protect forms, measure performance, and understand how content is used."] },
      { id: "use", title: "How cookies may be used", body: ["Freshira may use essential technologies needed to operate the website and optional technologies for preferences, analytics, or communications where appropriate consent has been obtained."] },
      { id: "controls", title: "Your controls", body: ["You can manage browser storage through your browser settings. Disabling essential cookies may affect some website functions. Any non-essential cookie controls should be presented where required by applicable law."] },
      sharedContact,
    ],
  },
  "/disclaimer": {
    eyebrow: "Website information",
    title: "Website Disclaimer",
    summary: "Important context for the information presented on Freshira’s website.",
    sections: [
      { id: "general", title: "General information", body: ["The content on this website is provided for general business and informational purposes. It is not legal, financial, medical, nutritional, or professional advice, and it should not be relied on as a substitute for advice tailored to your circumstances."] },
      { id: "accuracy", title: "Accuracy and availability", body: ["Freshira aims to keep website information useful and current, but cannot guarantee that every item is complete, current, or available in every location. Information may be updated without notice."] },
      { id: "external", title: "External services", body: ["Freshira is not responsible for the availability, content, or practices of external websites or services. You use third-party services according to their own terms."] },
      sharedContact,
    ],
  },
};

export function PolicyPage() {
  const { pathname } = useLocation();
  const policy = policies[pathname] ?? policies["/disclaimer"];
  return <PolicyLayout {...policy} />;
}
