import { ReactNode, useEffect, useRef, useState } from "react";
import { Link, NavLink, useLocation } from "react-router-dom";
import { ArrowUp, Heart, Leaf, Mail, MapPin, Menu, Search, ShoppingBag, Instagram, Linkedin, X } from "lucide-react";
import { useStore } from "@/context/store-context";

const navItems = [["Home", "/"], ["About", "/about"], ["Products", "/products"], ["Categories", "/categories"], ["Services", "/services"], ["Blog", "/blog"], ["Contact", "/contact"]];

export function Logo({ inverse = false }: { inverse?: boolean }) { return <Link to="/" className="group flex shrink-0 items-center gap-2.5" aria-label="Freshira home"><span className={`relative grid h-10 w-10 place-items-center rounded-[1.15rem] shadow-soft transition duration-300 group-hover:-rotate-6 ${inverse ? "bg-gold-400 text-brand-950" : "bg-primary text-white"}`}><Leaf size={21} strokeWidth={2.5} /><span className={`absolute -right-1 -top-1 h-2.5 w-2.5 rounded-full ${inverse ? "bg-white" : "bg-gold-400"}`} /></span><span className={`font-display text-[1.65rem] font-semibold tracking-tight ${inverse ? "text-white" : "text-brand-950"}`}>fresh<span className={inverse ? "text-gold-300" : "text-primary"}>ira</span></span></Link>; }

export function Header() {
  const [open, setOpen] = useState(false); const { cartCount, wishlist } = useStore(); const location = useLocation(); useEffect(() => setOpen(false), [location.pathname]);
  return <header className="sticky top-0 z-50 border-b border-brand-100/80 bg-background/90 backdrop-blur-xl"><div className="container flex h-[78px] items-center justify-between gap-5"><Logo /><nav className="hidden items-center gap-1 rounded-full border border-brand-100 bg-card/85 p-1.5 shadow-soft lg:flex" aria-label="Primary navigation">{navItems.map(([label, path]) => <NavLink key={path} to={path} className={({ isActive }) => `relative rounded-full px-3.5 py-2 text-xs font-bold transition-all ${isActive ? "bg-brand-950 text-white shadow-sm" : "text-brand-800 hover:bg-brand-50 hover:text-primary"}`}>{label}</NavLink>)}</nav><div className="flex items-center gap-1.5"><Link to="/products" className="grid h-10 w-10 place-items-center rounded-full text-brand-800 transition hover:bg-brand-100 hover:text-primary" aria-label="Search products"><Search size={18} /></Link><button type="button" className="relative grid h-10 w-10 place-items-center rounded-full text-brand-800 transition hover:bg-brand-100 hover:text-primary" aria-label="Wishlist"><Heart size={18} /><span className="absolute right-0.5 top-0.5 grid h-4 min-w-4 place-items-center rounded-full bg-gold-400 px-1 text-[9px] font-bold text-brand-950">{wishlist.length}</span></button><Link to="/cart" className="relative grid h-10 w-10 place-items-center rounded-full bg-primary text-white transition hover:bg-brand-700" aria-label="Cart"><ShoppingBag size={17} /><span className="absolute -right-1 -top-1 grid h-5 min-w-5 place-items-center rounded-full bg-gold-400 px-1 text-[10px] font-bold text-brand-950">{cartCount}</span></Link><button onClick={() => setOpen((value) => !value)} className="grid h-10 w-10 place-items-center rounded-full text-brand-900 hover:bg-brand-100 lg:hidden" aria-label="Toggle navigation" aria-expanded={open}>{open ? <X /> : <Menu />}</button></div></div>{open && <div className="border-t border-brand-100 bg-background px-4 pb-6 pt-3 shadow-card lg:hidden"><nav className="container grid gap-1" aria-label="Mobile navigation">{navItems.map(([label, path]) => <NavLink key={path} to={path} className={({ isActive }) => `rounded-2xl px-4 py-3.5 text-sm font-bold ${isActive ? "bg-brand-950 text-white" : "text-brand-900 hover:bg-brand-100"}`}>{label}</NavLink>)}</nav></div>}</header>;
}

export function Footer() { 
  return <footer className="relative overflow-hidden bg-brand-950 text-brand-100"><div className="absolute -right-24 -top-20 h-72 w-72 rounded-full border-[32px] border-gold-400/10" /><div className="container relative grid gap-10 py-12 sm:grid-cols-2 lg:grid-cols-[1.3fr_.7fr_.7fr_1fr] lg:py-14"><div><Logo inverse /><p className="mt-5 max-w-xs text-sm leading-6 text-brand-200">Fresh commerce and thoughtful supply chains, connecting good soil to good tables.</p><div className="mt-5 flex gap-2"><a href="https://www.instagram.com/" aria-label="Freshira Instagram" className="grid h-9 w-9 place-items-center rounded-full border border-brand-700 text-brand-200 transition hover:border-gold-300 hover:text-gold-300"><Instagram size={15} /></a><a href="https://www.linkedin.com/" aria-label="Freshira LinkedIn" className="grid h-9 w-9 place-items-center rounded-full border border-brand-700 text-brand-200 transition hover:border-gold-300 hover:text-gold-300"><Linkedin size={15} /></a><a href="mailto:hello@freshira.example" aria-label="Email Freshira" className="grid h-9 w-9 place-items-center rounded-full border border-brand-700 text-brand-200 transition hover:border-gold-300 hover:text-gold-300"><Mail size={15} /></a></div></div><div><h3 className="mb-4 font-display text-base font-semibold text-white">Explore</h3><ul className="space-y-2.5 text-sm text-brand-200">{[["About", "/about"], ["Products", "/products"], ["Categories", "/categories"], ["Services", "/services"], ["Journal", "/blog"]].map(([t, p]) => <li key={p}><Link className="transition hover:text-gold-300" to={p}>{t}</Link></li>)}</ul></div><div><h3 className="mb-4 font-display text-base font-semibold text-white">Support</h3><ul className="space-y-2.5 text-sm text-brand-200">{[["FAQ", "/faq"], ["Contact", "/contact"], ["Shipping", "/shipping-policy"], ["Returns", "/return-policy"]].map(([t, p]) => <li key={p}><Link className="transition hover:text-gold-300" to={p}>{t}</Link></li>)}</ul></div><div><h3 className="mb-4 font-display text-base font-semibold text-white">Legal</h3><ul className="space-y-2.5 text-sm text-brand-200">{[["Privacy Policy", "/privacy-policy"], ["Terms & Conditions", "/terms-and-conditions"], ["Refund Policy", "/refund-policy"], ["Cancellation Policy", "/cancellation-policy"], ["Cookie Policy", "/cookie-policy"], ["Disclaimer", "/disclaimer"]].map(([t, p]) => <li key={p}><Link className="transition hover:text-gold-300" to={p}>{t}</Link></li>)}</ul></div></div><div className="container border-t border-brand-800 py-6 text-center text-xs text-brand-300"><p>&copy; {new Date().getFullYear()} Freshira India Private Limited. All rights reserved.</p></div></footer>; 
}

function CursorFollower() {
  return null;
}

export function Layout({ children }: { children: ReactNode }) { 
  const [showTop, setShowTop] = useState(false); 
  useEffect(() => { 
    const onScroll = () => setShowTop(window.scrollY > 500); 
    window.addEventListener("scroll", onScroll); 
    return () => window.removeEventListener("scroll", onScroll); 
  }, []); 
  return <div className="min-h-screen overflow-x-hidden bg-[#FAF8F5]"><Header /><main>{children}</main><Footer /><a href="https://wa.me/" className="fixed bottom-5 left-5 z-40 grid h-12 w-12 place-items-center rounded-full bg-[#25D366] text-white shadow-lg transition hover:scale-110" aria-label="Contact Freshira on WhatsApp"><span className="text-lg font-bold">w</span></a>{showTop && <button onClick={() => window.scrollTo({ top: 0, behavior: "smooth" })} className="fixed bottom-5 right-5 z-40 grid h-11 w-11 place-items-center rounded-full bg-card text-primary shadow-card hover:bg-brand-50" aria-label="Back to top"><ArrowUp size={18} /></button>}</div>; 
}
